baseURL = "https://o365day2020.dotnetdev.it/"
languageCode = "it-it"
title = "MS365 Day"
theme = "infinity-hugo"
removePathAccents = true
publishDir = "docs"



# HTML before the closing </head>
[params]
customHead = ""

# Navigation
[params.navigation]
logo = "images/logo.png"
home = "Home"
about = "About"
service = "Services"
contact = "Contact"
cta = "Be a Part"
sponsor = "Sponsor"
agenda = "Agenda"

# Hero Area
[params.hero]
enable            = true
bg                = "images/header-bg.png"
title             = "MS365 Day 2020"
eventDate         = "06/11/2020"
subtitle          = "MS365 Day is a free online event dedicated to Low Code developer on Microsoft Platform"
btnText           = "Registrati"

# counter
disableCountdown  = false
countdownYear = "2020"
countdownMonth = "11"
countdownDay  = "06"
countdownHour  = "09"
countdownMin  = "00"
countdownSec  = "00"

# Sponsor Session
[params.sponsor]
enable = true
heading     = "The conference is organized by the DotNetCode community and is free, cost are supported by our sponsors."
titleplatinum   = "Platinum Sponsor"
titlegold   = "Gold Sponsor"
titletech   = "Tech Sponsor"
platinumSponsorEnable = true
goldSponsorEnable = true
techSponsorEnable = true

[[params.sponsor.sliderItemPlatinum]]
image   = "images/sponsor/microsoft.png"
link    = "https://www.microsoft.com"

[[params.sponsor.sliderItemPlatinum]]
image   = "images/sponsor/clusterreply.png"
link    = "https://www.reply.com/cluster-reply/it/"

[[params.sponsor.sliderItemPlatinum]]
image   = "images/sponsor/avanade.png"
link    = "https://www.avanade.com/it-it"

[[params.sponsor.sliderItemGold]]
image   = "images/sponsor/lobra.png"
link    = "https://www.lobrafutura.com/"

[[params.sponsor.sliderItemTech]]
image   = "images/sponsor/jetbrains.png"
link    = "https://www.jetbrains.com/"


# About Section
[params.about]
enable      = false
heading     = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam ipsa recusandae consequatur veniam, reiciendis odit quia eaque vel eius a."
description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ulla-mco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in Lorem ipsum dolor sit amet, consectetur adipisicing elit. Neque, aspernatur."

[[params.about.sliderItem]]
image   = "images/about/1.jpg"
[[params.about.sliderItem]]
image   = "images/about/2.jpg"
[[params.about.sliderItem]]
image   = "images/about/3.jpg"
[[params.about.sliderItem]]
image   = "images/about/2.jpg"


# Service Section
[params.service]
enable      = false
title       = "Find Better Solutions Build Better Products"
subtitle    = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et"
[[params.service.serviceItem]]
# give icon(themefisher icon font), title, description
# more about themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon    = "tf-strategy"
title   = "Fully Responsive"
description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
delay   = "0s"

[[params.service.serviceItem]]
# give icon(themefisher icon font), title, description
# more about themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon    = "tf-circle-compass"
title   = "Speed Optimized"
description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
delay   = "0.2s"

[[params.service.serviceItem]]
# give icon(themefisher icon font), title, description
# more about themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon    = "tf-anchor2"
title   = "Tons of Feature"
description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
delay   = "0.4s"

[[params.service.serviceItem]]
# give icon(themefisher icon font), title, description
# more about themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon    = "tf-globe"
title   = "Fully SEO Optimized"
description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
delay   = "0.6s"

[[params.service.serviceItem]]
# give icon(themefisher icon font), title, description
# more about themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon    = "tf-strategy"
title   = "Fully Responsive"
description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
delay   = "0.8s"

[[params.service.serviceItem]]
# give icon(themefisher icon font), title, description
# more about themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon    = "tf-circle-compass"
title   = "Speed Optimized"
description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
delay   = "1s"

[[params.service.serviceItem]]
# give icon(themefisher icon font), title, description
# more about themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon    = "tf-anchor2"
title   = "Tons of Feature"
description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
delay   = "1.2s"

[[params.service.serviceItem]]
# give icon(themefisher icon font), title, description
# more about themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon    = "tf-globe"
title   = "Fully SEO Optimized"
description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
delay   = "1.5s"

# Agenda Section
[params.agenda]
enable      = true


# Call to Action Section
[params.cta]
enable      = true
bg          = "images/call-to-action.png"
title       = "We Want you"
subtitle    = "Do you want partecipate to MS365 Day? You can teach, learn or help us as a staff member!"

eventbriteHomeButtonText = "Registrer to online event"
cfpHomeButtonText = "Call for paper"

eventbriteTitle = "Eventbrite"
eventbriteText = "The Office 365/Power Platform Day 2020 is a free one-day event organized by DotNetCode Community about Office 365, SharePoint Online and Power Platform."
eventbriteButtonText ="Registrer to online event"
eventbriteLink = "https://www.eventbrite.it/e/registrazione-microsoft-365-day-2020-120789694227?fbclid=IwAR3KP6wYkAwIaQxGtrF6xg0Odlg1fhrZJ6i9C8TN2FNMZ5R0sFOgIZau1jA"

cfpTitle = "Call For Paper"
cfpText = "Microsoft 365 Day is the event dedicated to the Microsoft Office Platform like Office 365, Sharepoint Online, Power Platform (Power BI, Power apps etc)."
cfpButtonText = "Call for paper"
cfpLink = "https://sessionize.com/rome-o365day-2020/"



[params.contact]
enable      = false
title       = "Get In Touch"
subtitle    = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex"
